### ISSUE TITLE
Android使用ValueSelector无法滑动至最后一个值

### ISSUE THREAD

**Issue by BitterLemonn** [ltttttttttttt/ComposeViews#102]
ValueSelector无法滑动至最后一个值，通过defaultSelectIndex设置为最后的index也无法将样式转化为selectedText的样式

**Comment by ltttttttttttt** [comment]
哪个平台?截个图看看

**Comment by ltttttttttttt** [comment]
代码,版本也发下

**Comment by BitterLemonn** [comment]
我已收到。

**Comment by BitterLemonn** [comment]
示例代码如下：
`@OptIn(ExperimentalFoundationApi::class)
@Composable
private fun TestSelector() {
    val nowDate = ZonedDateTime.now(ZoneId.of("Asia/Shanghai"))
    val list = (2010..nowDate.year).map { it.toString() } as ArrayList
    val state = remember { ValueSelectState() }
    ValueSelector(
        values = list,
        state = state,
        modifier = Modifier.fillMaxWidth(),
        cacheSize = 1,
        textSizes = arrayListOf(14.sp),
        selectedTextSize = 16.sp,
        selectedTextColor = Color(0xFF121212),
        textColors = arrayListOf(Color(0xFF9E9E9E))
    )
}

@Composable
@Preview(showBackground = true, showSystemUi = true)
private fun TestSelectorPreview() {
    TestSelector()
}`
使用平台 Android14 红米K50

https://github.com/user-attachments/assets/36e34e2a-2a08-4c32-9246-6d0b7be43fef

**Comment by BitterLemonn** [comment]
仓库版本 1.6.0.4 以及 1.6.11.2 都会出现这个情况 视频所示为1.6.0.4

**Comment by ltttttttttttt** [comment]
试下1.6.11.4

**Comment by BitterLemonn** [comment]
1.6.11.4可以滑动到最后一个值 但是使用state的get仍为到时第二个值

**Comment by ltttttttttttt** [comment]
我这边复现不了,我看了get的逻辑也很简单,如果取的索引不对,不清楚是不是系统api的问题

```
    /**
     * 获取当前选中的索引
     * Get current selected index
     */
    fun getSelectIndex(): Int = lazyListState.firstVisibleItemIndex % valueSize + (if (isLoop) cacheSize else 0)
```
