### ISSUE TITLE
VerticalRefreshableLayout 内容显示的问题

### ISSUE THREAD

**Issue by sansan-cc** [ltttttttttttt/ComposeViews#104]
*Target (Android, iOS ...):* Android

*ComposeViews versions:*  bom 2024.06.00

*Sample code*
![image](https://github.com/user-attachments/assets/92b0d7a4-a126-4e95-b553-e6d23f5266ba)

在数据量少比如一两条的时候，内容会居中，请问应该怎么修复啊QAQ

**Comment by ltttttttttttt** [comment]
给你的LazyColumn设置个maxSize?

**Comment by sansan-cc** [comment]
> 给你的LazyColumn设置个maxSize?

![image](https://github.com/user-attachments/assets/078b7dea-5925-417b-9015-21466a55822d)
试过，没有用，固定高度也没有用

but，我试过将 图片里RefreshLayout 的 fillMaxSize 去掉，那么排版就正常了，不正常的附两张图
![image](https://github.com/user-attachments/assets/33f4f10b-2083-4390-94b0-bd13e52ce73b)

![Screenshot_2024-08-20-20-06-13-727_com akcyf bmrj-edit](https://github.com/user-attachments/assets/4c0a1d13-88b0-4c1d-9d50-4495808e65c3)
![Screenshot_2024-08-20-20-06-06-723_com akcyf bmrj](https://github.com/user-attachments/assets/5227e915-7813-4806-94ef-b053a0727d20)
