### ISSUE TITLE
考虑新增一下照片选择器和图片预览么？

### ISSUE THREAD

**Issue by brandlee** [ltttttttttttt/ComposeViews#39]

**Comment by ltttttttttttt** [comment]
暂时不考虑,推荐使用成熟的方案,比如:
https://github.com/LuckSiege/PictureSelector

**Comment by brandlee** [comment]
> 

哇🤩，这个真的很赞啊，最近正在开发这一块，感谢！还有一个问题，Android大图浏览有成熟的库么？现在使用的是：https://github.com/jvziyaoyao/ImageViewer/blob/main/sample/src/main/java/com/origeek/viewerDemo/PreviewerActivity.kt

**Comment by ltttttttttttt** [comment]
差不多就是这一类的,不过上面我发的库也可以预览图片,音频和视频
![image](https://user-images.githubusercontent.com/23447567/220057957-668526c5-d8ab-4b57-a472-a85e8bcc841a.png)

**Comment by brandlee** [comment]
> 

嗯嗯，star数目很多，但是看issue，好像在Android13上面有好多问题

**Comment by ltttttttttttt** [comment]
Android13确实很坑,安卓10以后的文件系统改的东西还挺多的,一不留神就会出问题
现在用的也是这个,遇见了在改吧,没啥好办法,或者你找找有没有其他好用的库也给我说一声

**Comment by ltttttttttttt** [comment]
Android13确实很坑,安卓10以后的文件系统改的东西还挺多的,一不留神就会出问题
现在用的也是这个,遇见了在改吧,没啥好办法,或者你找找有没有其他好用的库也给我说一声

**Comment by brandlee** [comment]
> 

这个作者解决了，很不错
<img width="874" alt="image" src="https://user-images.githubusercontent.com/11416751/220062696-37fcbae5-a3ed-449c-981d-57bc6abdf284.png">
