### ISSUE TITLE
ComposePager Bug

### ISSUE THREAD

**Issue by brandlee** [ltttttttttttt/ComposeViews#41]
复现场景：
手指触摸向左Drag，然后快速向右swipe，这个时候定位错误：
![image](https://user-images.githubusercontent.com/11416751/221332168-fab3c28f-bf8a-4b45-b073-e6a97474f04c.png)

**Comment by ltttttttttttt** [comment]
这个图片我加载不出来emmm

**Comment by brandlee** [comment]
我重新上传一下看看
![image](https://user-images.githubusercontent.com/11416751/221460366-42f01050-bc88-4333-8718-f9311fcd31b8.png)

**Comment by brandlee** [comment]
![image](https://user-images.githubusercontent.com/11416751/221460494-9908164a-f590-4f0c-a2be-cc85c3ab85ae.png)

**Comment by ltttttttttttt** [comment]
要不你加我qq给我发一下?

**Comment by ltttttttttttt** [comment]
1764780379

**Comment by ltttttttttttt** [comment]
或者你分享个网盘,或发你项目里我下载也行

**Comment by brandlee** [comment]
> 

已经加好友了，麻烦同意一下

**Comment by ltttttttttttt** [comment]
io.github.ltttttttttttt:ComposeViews:1.3.8.1
