### ISSUE TITLE
使用banner时出现了报错 java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by Yetland** [ltttttttttttt/ComposeViews#59]
androidx.compose.runtime.snapshots.StateListIterator.validateModification (SnapshotStateList.kt:295)
kotlin.collections.CollectionsKt___CollectionsJvmKt.reverse (CollectionsKt___CollectionsJvm.kt:43)
com.lt.compose_views.compose_pager.ComposePagerKt.initContentList (ComposePager.kt:399)
com.lt.compose_views.compose_pager.ComposePagerKt.access$initContentList (ComposePager.kt:1)
com.lt.compose_views.compose_pager.ComposePagerKt.ComposePager (ComposePager.kt:115)
com.lt.compose_views.banner.BannerKt$Banner$4.invoke (Banner.kt:99)
com.lt.compose_views.banner.BannerKt$Banner$4.invoke (Banner.kt:97)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:107)
androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:228)

**Comment by Yetland** [comment]
![image](https://github.com/ltttttttttttt/ComposeViews/assets/7824187/010a22da-5ecc-4076-a9d6-c7e61e2910e3)
报错定位的行数是399这一行

**Comment by ltttttttttttt** [comment]
下周了我看看

**Comment by ltttttttttttt** [comment]
你是怎么操作出现的?

**Comment by Yetland** [comment]
我把数据源改成mutableStateListOf试试看。报错挺多的。

**Comment by Yetland** [comment]
之前使用的是mutableListOf，这个数据线程不安全，使用mutableStateListOf可能会解决

**Comment by Yetland** [comment]
![image](https://github.com/ltttttttttttt/ComposeViews/assets/7824187/5d832822-cebf-4aa0-86df-b6bda78b06c3)

**Comment by Yetland** [comment]
banner在android5.0 & 6.0中会报错，你可以自己试一下

**Comment by ltttttttttttt** [comment]
ok

**Comment by ltttttttttttt** [comment]
你的代码是怎么写的?我在android5中没有复现出来

**Comment by ltttttttttttt** [comment]
找到问题了,就是低版本的reverse方法有问题,晚上我再发一版

**Comment by ltttttttttttt** [comment]
1.4.0.12
