### ISSUE TITLE
加载更多的时候 无法往上继续查看已有的内容

### ISSUE THREAD

**Issue by artillerymans** [ltttttttttttt/ComposeViews#60]

**Comment by ltttttttttttt** [comment]
目前是这样设计的,后续我看能不能加一个开关

**Comment by GostGrimmy** [comment]
这个地方注释
//如果是刷新中状态,就拒绝对刷新区域和上下区域滚动
//        if (refreshLayoutState.refreshContentState.value == RefreshContentStateEnum.Refreshing) {
//            return if (orientationIsHorizontal)
//                Offset(available.x, 0f)
//            else
//                Offset(0f, available.y)
//        }
本地编译

**Comment by ltttttttttttt** [comment]
dev分支改好了,最近忙一直没机会用mac去发版(支持iOS后得用mac才能发版)

**Comment by ltttttttttttt** [comment]
今天晚上我发一下
