### ISSUE TITLE
ColumnScope.AppBar的LazyColumn内容比较少的情况下折叠出现异常

### ISSUE THREAD

**Issue by songwenju** [ltttttttttttt/ComposeViews#68]
如设置items count 为2，向上折叠时，上面有空白，代码
@OptIn(ExperimentalFoundationApi::class)
    @Composable
    fun ColumnScope.AppBar() {
        val lazyListState = rememberLazyListState()
        ScrollableAppBar(
            title = "toolbar",
            background = resourcePainter("top_bar_bk"),
            maxScrollPosition = maxDp,
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth(),
            //onScrollStop = scrollStop(lazyListState)
        ) {
            LazyColumn(
                contentPadding = PaddingValues(top = maxDp),
                modifier = Modifier.fillMaxSize(),
                state = lazyListState,
            ) {

                items(2) { index ->
                    Text(
                        "I'm item $index", modifier = Modifier.padding(16.dp)
                    )
                }
            }
        }
    }
有啥好的解决办法吗？

**Comment by ltttttttttttt** [comment]
晚上我再发一版,你到时候再试试

**Comment by ltttttttttttt** [comment]
1.5.1.2
