### ISSUE TITLE
ios 日期控件会有位移

### ISSUE THREAD

**Issue by liufeng382641424** [ltttttttttttt/ComposeViews#77]
![111](https://github.com/ltttttttttttt/ComposeViews/assets/74255024/07261efa-6beb-433d-abc5-f080fe791ab0)

**Comment by liufeng382641424** [comment]
ios 版本16.3 型号XR
我应该怎么修复它？

**Comment by ltttttttttttt** [comment]
用的哪个版本的库?

**Comment by liufeng382641424** [comment]
1.5.10.1，目前看是最新的库

**Comment by liufeng382641424** [comment]
android是正常的，在ios上才会有这个问题，并不是一直都出现位移，持续滑动偶尔也会正常，滑动越快，位移的偏差越大

**Comment by liufeng382641424** [comment]
可以了，非常感谢，时间最大值如果能加上月跟日会更友好，能换年月日顺序吗？或者让私有类也公开我们继承重写也行。

**Comment by ltttttttttttt** [comment]
你可以直接copy一份DateSelector 来实现符合自己需求的,代码很简单

**Comment by ltttttttttttt** [comment]
又改了点问题,升级到1.5.10.4吧

**Comment by liufeng382641424** [comment]
![WX20240119-124711@2x](https://github.com/ltttttttttttt/ComposeViews/assets/74255024/ff4ed762-c935-4b42-a83b-90f0891188d9)
选择器在滑动到底部后一直往上还能继续滑动

**Comment by ltttttttttttt** [comment]
代码发一下

**Comment by ltttttttttttt** [comment]
是只有ios吗?

**Comment by liufeng382641424** [comment]
fun SelectDialog(list: List<String>, onDismiss: () -> Unit, callback: (Int, String) -> Unit) {
    val state = ValueSelectState()
    Dialog(onDismissRequest = onDismiss, properties = DialogProperties(usePlatformDefaultWidth = false)) {
        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.BottomCenter) {
            Column(
                modifier = Modifier.background(color = White, shape = RoundedCornerShape(topEnd = 15.dp, topStart = 15.dp)).padding(15.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Row {
                    Text(modifier = Modifier.padding(5.dp).clickable { onDismiss() }, text = strings("cancel"), fontWeight = FontWeight.Medium, fontSize = 14.sp, color = C666)
                    Spacer(Modifier.weight(1f))
                    Text(modifier = Modifier.padding(5.dp).clickable {
                        onDismiss()
                        callback(state.getSelectIndex(), list[state.getSelectIndex()])
                    }, text = strings("sure"), fontWeight = FontWeight.Medium, fontSize = 14.sp, color = Blue)
                }
                Box {
                    ValueSelector(
                        modifier = Modifier.fillMaxWidth().padding(vertical = 10.dp),
                        values = list.toArrayList(),
                        state = state,
                        textSizes = arrayListOf(14.sp, 14.sp),
                        selectedTextSize = 16.sp,
                        textColors = arrayListOf(C999, C999),
                        selectedTextColor = Blue
                    )
                    Column(Modifier.fillMaxWidth().align(Alignment.Center)) {
                        Divider(Modifier.fillMaxWidth().height(1.dp), Gray10)
                        VerticalSpace(48)
                        Divider(Modifier.fillMaxWidth().height(1.dp), Gray10)
                    }
                }
            }
        }
    }
}

**Comment by liufeng382641424** [comment]
是的只有ios有这个情况，我感觉是不是ios特有的回弹动效导致这个bug

**Comment by ltttttttttttt** [comment]
测试了下猜测可能是bug,等待反馈中: https://github.com/JetBrains/compose-multiplatform/issues/4148
