### ISSUE TITLE
Android使用DateSelector问题汇总

### ISSUE THREAD

**Issue by brandlee** [ltttttttttttt/ComposeViews#79]
在Android手机上使用DateSelector，设置isLoop为true的时候，数组越界，直接crash

**Comment by brandlee** [comment]
然后在有的华为手机上无法滑动到12月份

**Comment by ltttttttttttt** [comment]
我看下

**Comment by ltttttttttttt** [comment]
1.5.10.4 这个解决了越界的崩溃问题,另一个无法滑动到12月份我这边没有复现,不过我大概知道什么原因了,我试试复现后给改一下

**Comment by ltttttttttttt** [comment]
试下1.6.11.4
