### ISSUE TITLE
Banner 能否支持contentPadding,pageSpacing

### ISSUE THREAD

**Issue by sceneren** [ltttttttttttt/ComposeViews#99]
*Target (Android, iOS ...):*

*ComposeViews versions:*

*Sample code*

**Comment by ltttttttttttt** [comment]
详细描述下需求?

**Comment by sceneren** [comment]
<img width="275" alt="image" src="https://github.com/ltttttttttttt/ComposeViews/assets/6612998/13d89a06-b721-44c9-9035-f357318b2d52">
类似这种banner

**Comment by ltttttttttttt** [comment]
回头我参考官方Pager实现下

**Comment by ltttttttttttt** [comment]
你可以试下dev分支的ContentPaddingA页面,看看符不符合效果,我没有用跟Pager一样的api去实现
![image](https://github.com/ltttttttttttt/ComposeViews/assets/23447567/0339ba17-37d8-499d-8863-f2fd120f5eb1)
![image](https://github.com/ltttttttttttt/ComposeViews/assets/23447567/d4105ba6-faa4-4c83-ba9d-e6261ac686ec)

**Comment by sceneren** [comment]
好的，空了我试试

**Comment by sceneren** [comment]
效果是没啥问题的，就是banner控件能否支持？

**Comment by ltttttttttttt** [comment]
可以支持,回头我发一版

**Comment by ltttttttttttt** [comment]
1.6.11.2
